### ISSUE TITLE
WIP -> Transportation: Excess Supply, Overwhelming Demand

### ISSUE THREAD

**Issue by ben-chaney** [hackoregon/civic#75] opened 2018-05-03 06:52 UTC
# Story Card Request

**Project:** Transportation
**Card Title:** Excess Supply (or Capacity), Overwhelming Demand

## Description / Wireframe
Map (or non-geographic summary by line or stop) showing where excess transit capacity (service-miles traveling at low passenger load)  and unmet transit demand (service-miles traveling at crowded passenger load) are distributed.  Animate over time? 

## Context
Provide insight as to where new capacity should be provided.

> Why is this important? This information will be used to prioritize and contextualize story cards.

## Data Details (APIs)
Trimet Congestion

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins.
> In addition, any calculations on the source data should be described.

**Comment by code-farmhouse** [comment] 2018-05-06 19:39
possible duplicate of [76](https://github.com/hackoregon/civic/issues/76)

**Comment by gouldc2** [comment] 2018-05-06 23:11
This could be entirely within the Stop_Event table from Congestion files. 
Has: on/offs, stop ID, route, date, time, estimated passenger load

**Comment by jaronheard** [comment] 2018-05-16 03:28
Per our discussion, to show this visually, we could determine:
Percent of busses with a high load
Percent of busses with a low load

And show this by showing colors along the transit lines on a map.
- [ ] How are we defining "high load"?
- [ ] How are we defining "low load"?

**Comment by ben-chaney** [comment] 2018-05-16 03:58
High and Low load would be defined using the ESTIMATED_LOAD attribute from the trimet_stop_event table. This is an estimate of number of passengers on the vehicle upon departing the stop.  To get to a "high load" and "low load" flag, we'll need to determine the vehicle type based on either the vehicle number or the route number, then determine the seating capacity and/or the standing capacity of the vehicle. From that, we define a maximum passenger load threshold for "low load" and a minimum passenger load threshold for "high load."  

There's tons of industry and academic resources out there that address Quality of Service for transit passengers, one of these might be a good option for determining the max/min thresholds.

**Comment by benleelawrence** [comment] 2018-05-22 04:28
![](https://lh4.googleusercontent.com/6Wmu9HFpjWlCBAsLCsgQYh3Z7YhWeLeW9sSyR39iuXULZLFiXdDC1qbF54zcTRTc_B4UmxXeWF3Q7HsxGA9D=w3768-h2046-rw)
2015 vehicle capacities from https://trimet.org/pdfs/tip/serviceguidelines.pdf

**Comment by jaronheard** [comment] 2018-06-28 00:21
Closing as part of post-2018 project season cleanup

**Closed by jaronheard** 2018-06-28 00:21 UTC
Labels: card, congestion, transportation
