### ISSUE TITLE
Budget infinitely running test

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#22] opened 2017-11-09 22:45 UTC
The budget package works, but infinitely runs tests until it eventually exits node with an error.

I spent too long looking into this.

The infinite test looping is caused by the --watch parameter being passed to mocha. Something, somewhere, is changing that is triggering mocha to rerun tests. Not sure what file is changing, so if anyone wants to look into this, this is where to start.

Also, there is a separate issue:
There is an UnhandledPromiseRejectionWarning being thrown by the request test. This appears to be a mocha issue:
https://github.com/mochajs/mocha/issues/3009

**Comment by DavideDaniel** [comment] 2017-11-11 21:06
This is a duplicate of #15 .. either we should close this or alter it to handle the separate issue mentioned here.

**Closed** 2017-11-12 06:52 UTC
