### ISSUE TITLE
WIP -> Housing: Policy Inventory (Name TBD)

### ISSUE THREAD

**Issue by danmelton** [hackoregon/civic#60] opened 2018-04-26 03:20 UTC
# Story Card Request

**Project: Housing**
**Card Title: Housing Policy Inventory**

## API Details

> Include all API calls that will need to be made, including all params and the possible
> values for the params. The more specific the better! This will help prevent back and forth
> and ultimately make for a quicker turnaround.

> If you do not have an API yet, it can be added later, but it is mandatory before a frontend
> developer works on this ticket.

## Client-side Calculations

> If the data from the API is not pre-calculated, please include all formulas here.
> e.g., `affordable = rent < monthlyIncome * 0.3`

## Data Sources

> All cards should trace back to their data origins. Include public links to those origins
> So card developers can embed the links in the card.

## Wireframes

> Include a detailed description and/or image that describes your story or visualization using
> the data described above. This can be as detailed as a wireframe, or as simple as a description
> such as a bar chart that shows variable A on the X-axis and variable B on the Y-axis.

> Once you have a wireframe, Include an embedded image of the card design by pasting an image from
> your clipboard or using the image uploader tool under this text box. This is mandatory before a
> front-end developer works on this ticket.

> Also include a link to a Figma design if you have one.

**Comment by jaronheard** [comment] 2018-05-11 03:27
@danmelton is this a duplicate?

**Comment by jaronheard** [comment] 2018-05-21 22:08
Duplicate of #106

**Closed by jaronheard** 2018-05-21 22:08 UTC
Labels: card, housing
